---
- name: Get Linux Host Information
  hosts: all
  gather_facts: yes
  tasks:
  - name: Get Hostname
    shell: hostname
    register: hostname_result
    
  - name: Get OS
    shell: cat /etc/os-release | grep "PRETTY_NAME" | awk -F '"' '{print $2}'
    register: os_result

  - name: Get OS Release Version
    shell: cat /etc/os-release | grep "VERSION_ID" | awk -F '=' '{print $2}'
    register: os_version_result

  - name: Get Disk Capacity
    shell: df -h | grep "/$" | awk '{print $2}'
    register: disk_capacity_result

  - name: Get Disk Usage
    shell: df -h | grep "/$" | awk '{print $3}'
    register: disk_usage_result

  - name: Save Output to File with Hostname as prefix
    copy:
      content: |
        Hostname: {{ hostname_result.stdout }}
        Operating System: {{ os_result.stdout }}
        Operating System Release Version: {{ os_version_result.stdout }}
        Disk Capacity: {{ disk_capacity_result.stdout }}
        Disk Usage: {{ disk_usage_result.stdout }}
      dest: "/tmp/{{ hostname_result }}"
    when: hostname_result.stdout and os_result.stdout and os_version_result.stdout and disk_capacity_result.stdout and disk_usage_result.stdout
  
  - name: Display Information
    debug:
      msg: "{{ hostname_result.stdout }} \n {{ os_result.stdout }} \n {{ os_version_result.stdout }} \n {{ disk_capacity_result.stdout }} \n {{ disk_usage_result.stdout }}"
      
#TODO Transfer file via SCP back to AWX
#  - name: Transfer file via SCP
#    local_action:
#      module: scp
#      src: "/tmp/{{ inventory_hostname }}_inventory_information"
#      dest: andy@andy-awxnode-test:~/awx-host-info/
#      username: andy
