---
- name: Get Linux Host Information
  hosts: all
  gather_facts: yes
  tasks:
  - name: Get Hostname
    shell: hostname
    register: hostname_result
    
  - name: Get OS
    shell: cat /etc/os-release | grep "PRETTY_NAME" | awk -F '"' '{print $2}'
    register: os_result

  - name: Get OS Release Version
    shell: cat /etc/os-release | grep "VERSION_ID" | awk -F '=' '{print $2}'
    register: os_version_result

  - name: Get Disk Capacity
    shell: df -h | grep "/$" | awk '{print $2}'
    register: disk_capacity_result

  - name: Get Disk Usage
    shell: df -h | grep "/$" | awk '{print $3}'
    register: disk_usage_result

  - name: Get Apache Version
    shell: apache2ctl -v | grep "Server version" | awk '{print $3, $4}'
    register: apache_version_result

  - name: Get Apache Status
    shell: apache2ctl status | grep "Apache Server Status"
    register: apache_status_result

  - name: Get Java Version
    shell: java -version 2>&1 | awk -F '"' '/version/ {print $2}'
    register: java_version_result

  - name: Get MySQL Version
    shell: mysql -V | awk '{print $5}'
    register: mysql_version_result

  - name: Save Output to File with Hostname as prefix
    copy:
      content: |
        Hostname: {{ hostname_result.stdout }}
        Operating System: {{ os_result.stdout }}
        Operating System Release Version: {{ os_version_result.stdout }}
        Disk Capacity: {{ disk_capacity_result.stdout }}
        Disk Usage: {{ disk_usage_result.stdout }}
        Apache Version: {{ apache_version_result.stdout }}
        Apache Status: {{ apache_status_result.stdout }}
        Java Version: {{ java_version_result.stdout }}
        MySQL Version: {{ mysql_version_result.stdout }}
      dest: "/tmp/{{ hostname_result.stdout }}_inventory_information.txt"
    when: hostname_result.stdout and os_result.stdout and os_version_result.stdout and disk_capacity_result.stdout and disk_usage_result.stdout and apache_version_result.stdout and apache_status_result.stdout and java_version_result.stdout and mysql_version_result.stdout

  - name: Print Information
    debug:
      msg: |
        Hostname: {{ hostname_result.stdout }}
        Operating System: {{ os_result.stdout }}
        Operating System Release Version: {{ os_version_result.stdout }}
        Disk Capacity: {{ disk_capacity_result.stdout }}
        Disk Usage: {{ disk_usage_result.stdout }}
        Apache Version: {{ apache_version_result.stdout }}
        Apache Status: {{ apache_status_result.stdout }}
        Java Version: {{ java_version_result.stdout }}
        MySQL Version: {{ mysql_version_result.stdout }}
