---
- name: Get Linux Host Information
  hosts: all
  gather_facts: yes
  tasks:
  - name: Get Hostname
    shell: hostname
    register: hostname_result
    
  - name: Get OS
    shell: cat /etc/os-release | grep "PRETTY_NAME" | awk -F '"' '{print $2}'
    register: os_result

  - name: Get OS Release Version
    shell: cat /etc/os-release | grep "VERSION_ID" | awk -F '=' '{print $2}'
    register: os_version_result

  - name: Get Disk Capacity
    shell: df -h | grep "/$" | awk '{print $2}'
    register: disk_capacity_result

  - name: Get Disk Usage
    shell: df -h | grep "/$" | awk '{print $3}'
    register: disk_usage_result

  - name: Check if Java is installed
    shell: java -version
    register: java_result
    ignore_errors: yes

  - name: Check if Apache2 is installed
    shell: apache2 -v
    register: apache2_result
    ignore_errors: yes

  - name: Check if MySQL is installed
    shell: mysql -V
    register: mysql_result
    ignore_errors: yes

  - name: Save Output to File with Hostname as prefix
    copy:
      content: |
        Hostname: {{ hostname_result.stdout }}
        Operating System: {{ os_result.stdout }}
        Operating System Release Version: {{ os_version_result.stdout }}
        Disk Capacity: {{ disk_capacity_result.stdout }}
        Disk Usage: {{ disk_usage_result.stdout }}
        Java: {{ java_result.rc == 0 }}
        Apache2: {{ apache2_result.rc == 0 }}
        MySQL: {{ mysql_result.rc == 0 }}
      dest: "/tmp/{{ hostname_result.stdout }}_inventory_information.txt"
    when: hostname_result.stdout and os_result.stdout and os_version_result.stdout and disk_capacity_result.stdout and disk_usage_result.stdout

  - name: Print Information
    debug:
      msg: |
        Hostname: {{ hostname_result.stdout }}
        Operating System: {{ os_result.stdout }}
        Operating System Release Version: {{ os_version_result.stdout }}
        Disk Capacity: {{ disk_capacity_result.stdout }}
        Disk Usage: {{ disk_usage_result.stdout }}
        Java: {{ java_result.rc == 0 }}
        Apache2: {{ apache2_result.rc == 0 }}
        MySQL: {{ mysql_result.rc == 0 }}
